# This file tells the Railway builder exactly how to build and run our app.

# 1. Specify the providers and versions to install in the build environment
[providers]
dotnet = "8"

# 2. Specify the command to start the application after the build
# (The path has been corrected here)
[start]
cmd = "dotnet MoodleTrueFalse/bin/Release/net8.0/MoodleTrueFalse.dll"